### ISSUE TITLE
Where did elazar come from?

### ISSUE THREAD

**Issue by greydnls** [elazar/amas#1]

**Comment by elazar** [comment]
When I first became active on Freenode back around '05 or '06, I needed a nick. I didn't want to use my real name, partly from the insecurities involved in being new to the community.

While I never did much with it -- becoming more serious about writing fiction, for example -- I used to have a knack for making up names. Elazar didn't have a particular origin; I just made it up out of nothing.

However, it is apparently an actual name used in what I can only presume is a country in the Middle East. On occasion, I've had a random person PM me on IRC speaking in a language I don't understand. When I clarify that, the person usually says something to the effect of "oh" and the conversation generally ends there.

All that said, while @auroraeosrose still likes to call me "E-laser," the "correct" pronunciation is "ehl-uh-zahr."

<img src="http://3.bp.blogspot.com/-XINLKyTGKw4/UWaOCalHl4I/AAAAAAAAA90/CYnufSVusCs/s1600/Dr+Evil+Laser.jpg" />

**Comment by wlturland** [comment]
The way I remember it is that you picked it up as a mis-read of Elzar from Futurama when I was binge-watching during the youngest child's pregnancy. https://www.youtube.com/watch?v=o4BOZcDMw_A

**Comment by elazar** [comment]
Hm... might've been, yeah. Hard to say this long after the fact what contributed inspiration at that point.

**Comment by wlturland** [comment]
Pretty sure that was it, because of course I went on my usual Emeril rant after that, and you started making fun of me.
