### ISSUE TITLE
What qualities/skills should every junior developer possess? 

### ISSUE THREAD

**Issue by CarlMungazi** [elazar/amas#7]

**Comment by elazar** [comment]
For a junior developer, I believe these are the most important:
1. **Patience**. Software and the process of developing it is often complicated, nuanced, and rife with caveats. I often say that if most people knew the reality of this circumstance, they'd be surprised that software ever works at all. Likewise, getting to a point where you feel like you're productively developing software requires a fair amount of knowledge, so be patient with yourself and those who attempt to help you learn.
2. **Desire to learn**. Not only is software development a field involving an expansive amount of knowledge, but it's also a field that changes and evolves rapidly and often. Learning is something you will do continuously and indefinitely for as long as you are a developer. Be sure it's something you enjoy. Likewise, [try not to let it overwhelm you](http://matthewturland.com/2012/12/08/on-what-to-learn/).
3. **Desire to improve**. This is somewhat interrelated to a desire to learn, but it's not uncommon to learn just enough about something to get by and then stop. If you have no desire to improve, your code will look the same in six months as it does now, and that's a visible sign that you are stagnating and not growing as a developer. If you want to exceed the position of a junior developer, you must devote time and energy to honing and improving your craft.

Past that point, there are of course [other traits](http://matthewturland.com/2014/01/24/how-to-be-a-great-developer/) that are ideal to cultivate.
